src/AppConstants.js
src/SmartComponents/Cards/VulnerabilityCard.js

Two things here:
* The CVSS number is incresed from 7 to 8. Vulnerability UI has predefined ranges on CVSS_Filter as there is no PF4 slider yet and if we want to redirect the user to filtered table, it needs to match predefined ranges. It was agreed to have a range "8 - 10".
* This is more a temporal parameter until the variable cvvs range gets resolved. However at least the user is now redirected to filtered list.

Link should redirect user to a filtered CVE table

---

src/SmartComponents/Cards/ComplianceCard.js

Refs: https://projects.engineering.redhat.com/browse/RHCLOUD-1465
Currently, periodic decimals are shown, which force the numbers to show up outside of the donut chart.

Truncate Compliance score to integer

---

build/messages/src/Messages.json
locales/data.json
locales/translations.json
src/App.scss
src/AppActions.js
src/AppConstants.js
src/AppReducer.js
src/Messages.js
src/PresentationalComponents/Dashboard/Dashboard.js
src/SmartComponents/Advisor/Advisor.js
src/SmartComponents/Advisor/Constants.js
src/SmartComponents/Advisor/StackChart.js

s all done, good enough for a first cut, **everything is live**, n should redirect like a 💎 
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-4638
~despite what mocks say, gonna rename this card `Advisor Recommendations` as per BU request
follows mocks here https://marvelapp.com/a5c8bcg/screen/66136610~
~TODO~
* ~figure out what the chart theme is (colors), implement it in both legend and chart~
* ~bullet chart order is dynamic, smallest to largest, figure out if this is ok or if it needs to be static~
* ~hook up the api, easy peasy 🍋 squeezy~
* ~make chart clicks and legend clicks to go insights rules table with correct filter set~
* solve the Pin nut Crisis 2020

Adds Advisor Recommendations card

---

src/App.scss
src/SmartComponents/Advisor/_Advisor.scss

There were some rogue styles affecting the left nav. Since we can still affect chroming styles, we need to scope the styles correctly. Also, remove the PF sass imports for regular ol css vars.
If we did wan to scope the font-size for `a` to everything in the dashboard, we should scope it to the main area so we still don't affect chrome.

Scope styles to cards, use PF vars when needed

---

src/index.html

The `@@env` tag needs a slash before it after we updated the config, but I missed it.

fix esi tag

---

src/App.scss
src/SmartComponents/Compliance/ComplianceCard.scss

Empty state bodies should be `--pf-global--FontSize--sm` size
This makes remediations empty state body smaller and moves the compliance style to the app level
[if needed]
@kybaker

make empty state bodies small text

---

src/SmartComponents/SubscriptionsUtilized/Constants.js
src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.scss

- Applies a product link button towards the Subscription Watch GUI for both RHEL and OpenShift
- Expand tooltips hover area with the button used for the aforementioned "link"
- Cleans up the productsHaveData and instead now uses a length check for "products having data" to account for displaying the pending state fully
- Relates https://github.com/RedHatInsights/curiosity-frontend/issues/266
- It appears the text decoration on the links is being overridden "on hover", however this appears consistent with behavior that happens on this link as well...
@kybaker
closes #130

fix subscriptions utilized link and tooltip hover area

---

src/App.js

When App.js loaded, if a user didn't have any permissions, there was no way you can map over an undefined object and check to see if it includes anything.
This skips that check and just uses the default `false` value if nothing is returned.

make sure permissions exist before loading stuff

---

src/ChartTemplates/StackChart/StackChartTemplate.js

addresses    https://github.com/RedHatInsights/insights-dashboard/issues/137#issuecomment-620217448 
addresses     https://github.com/RedHatInsights/insights-dashboard/issues/137#issuecomment-620229864

Adjusts stack chart color, tooltip position

---

src/AppConstants.js
src/SmartComponents/Compliance/ComplianceCard.js

This makes it fetch only reports which have at least one result. In
addition to that, it fixes a few other things that are outdated since
summit:
* Aria attributes were wrong
* Chart was showing the compliant vs non-compliant wrong
* Link to each report or more policies was wrong
* 'More reports' link is only shown if there are 4 or more.
@kybaker

Compliance: Fetch reports with results

---

src/SmartComponents/Compliance/ComplianceCard.js

The operation to show "more policies" is wrong - if you have just 1 policy, it would do "3 - 1 > 1" and try to show you more links. The subtraction order is wrong, it should be the opposite "1 - 3 > 1" - in this case, it would not show you any links. 
[if needed]
@kybaker

Fix wrong operation to compute link to 'more policies'

---

src/AppConstants.js

Speed up inventory API calls by only using per_page=1, this will be updated in the future when `0` is supported. All we need is the metadata, no actual hosts.
nothing changed

use per_page=1 for inventory to speed up calls

---

src/SmartComponents/SubscriptionsUtilized/Constants.js
src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js

- ~Scope your styles to your individual card~
- ~You are using translations when necessary with proper plural/singular modifications~
- ~Attach screenshots (before and after)~
- ~Make sure that all text in blue is populated with the correct link. If you're unsure what the url should be, just ask!~
This applies the RHSM Tally and Capacity error code check to determine if a 403 is actually "opt-in" instead of a generic 403 status check.
Behind the scenes error code work. The before and after should visually be the exact same.
Directly relates to RHSM API changes
- [Curiosity/Subs Watch issue 281](https://github.com/RedHatInsights/curiosity-frontend/issues/281)
And segues into user permissions, RBAC
- [Curiosity/Subs Watch issue 300](https://github.com/RedHatInsights/curiosity-frontend/issues …

update subscriptions utilized card, apply error code for opt-in

---

src/ChartTemplates/StackChart/StackChartTemplate.js
src/ChartTemplates/StackChart/_StackChartTemplate.scss
src/SmartComponents/Advisor/Advisor.js
src/SmartComponents/Vulnerability/VulnerabilityCard.js

In response to [RHCLOUD-8045](https://projects.engineering.redhat.com/browse/RHCLOUD-8045), this PR adds a window listener to correct the size of the tooltips.
Currently, we have a scalable chart.
@kybaker

Fix StackChart Tooltip size

---

src/SmartComponents/Remediations/RunStatus.js

This PR adds a Tooltip to a remediation's name (as it appears in the remediations template card) if the length of the name is greater than 20. I chose 20 because it aligns well with the `## more remediations` button length.
@kybaker

Add Tooltip for longer remediation names

---

src/SmartComponents/Compliance/ComplianceCard.js

fixes https://projects.engineering.redhat.com/browse/RHICOMPL-755
that leading slash leads to the beta location gettin eaten up

Compliance button urls redirect correctly on beta

---

src/SmartComponents/PatchManager/PatchManagerCard.js

#124  What
Patchman Pie chart legend colour mismatch is fixed. 
[before screenshot]
[after screenshot]
@kybaker

fix(Patch PieChart): pie chart legend color mistmatch

---

src/App.js
src/AppActions.js
src/AppConstants.js
src/AppReducer.js
src/SmartComponents/Advisor/Advisor.js
src/SmartComponents/Advisor/Constants.js

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-9044
on filter change, we go into loading screen for the advisor widget then display the results

Adds global filter support to dashboard and advisor card 🤗🍍🐞

---

src/SmartComponents/Advisor/Advisor.js

also, the count returned is 0, no need for the `|| 0`

If there are no incidents, advisor incident text is green

---

src/SmartComponents/Advisor/Advisor.js

This PR fixes https://issues.redhat.com/browse/ADVISOR-1377. We are seeing `NaN` as the pagination limit when navigating from the Advisor dashboard card to the Advisor recommendations page.
@kybaker

Add ternary operator for url creation in advisor card

---

package-lock.json
package.json
src/SmartComponents/Advisor/Advisor.js
src/SmartComponents/SystemInventory/SystemInventoryCard.js
src/Utilities/Common.js

Enable global filter tags and sap_system to be passed down to inventory enpoints. Use `generateFilter` from frontend components (it has been added recentrly) in order to properly style the filter for inventory to be `filter[system_profile][sap_syste]: true`. This function can later help us to calculate SAP_SIDs as well.
[if needed]
@kybaker

Pass sap_system and tags to inventory enpoints

---

src/App.js
src/PresentationalComponents/ZeroState/_zero-state.scss

When user access dashboard, global filter is hidden all the time, this is caused by CSS rule, instead of hiding this trough CSS hide it trough chrome API.
@ryelo @AllenBW

Do not hide global filter trough CSS

---

src/AppConstants.js
src/SmartComponents/Compliance/ComplianceCard.js

Related to recent feature COMP-E-152, compliance reports should be
grouped by policy. This change should fix the dashboard to reflect the
results shown in the new compliance reports page.
In addition, unsupported reports are no longer counted in the compliant or total (renamed to test_result_count) count. For now, those hosts are not shown in the dashboard at all.
Requires https://github.com/RedHatInsights/compliance-backend/pull/677
@kybaker
Signed-off-by: Andrew Kofink <akofink@redhat.com>

fix(compliance): RHICOMPL-1181 Group results by policy

---

src/Routes.js

Fixes hot reload issue:
```bash
｢wdm｣: Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
/Users/mattnolting/Web/insights-master/insights-dashboard/dist/Dashboard.21df37310ce7ebf394cc.hot-update.js
/Users/mattnolting/Web/insights-master/insights-dashboard/dist/dashboard.21df37310ce7ebf394cc.hot-update.js
```
In short, this is why we had this issue. We have a file called `Dashboard` and a custom lazy import chunk also called `Dashboard` set by `/* webpackChunkName: "Dashboard" */`. But the hot-update chunks are lowercased. The first build passes because there are no hot-loaded files yet. After any change in `Dashboard.js` file, webpack generates …

Rename custom Dashboard webpack chunk name.

---

src/Utilities/Common.js

fixes https://issues.redhat.com/browse/ADVISOR-1587

Accommodate removal of "all workloads" workload 🐚 

---

src/PresentationalComponents/Template/ExpandableCardTemplate.js
src/SmartComponents/Advisor/Advisor.js
src/SmartComponents/Advisor/Advisor.scss
src/SmartComponents/Compliance/ComplianceCard.js
src/SmartComponents/NewRules/NewRules.js
src/SmartComponents/PatchManager/PatchManagerCard.js
src/SmartComponents/Remediations/RemediationsCard.js
src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
src/SmartComponents/SystemInventory/SystemInventoryHeader.js
src/SmartComponents/Vulnerability/VulnerabilityCard.js

fixes https://issues.redhat.com/browse/ADVISOR-1656
so now we persist card dropdown state through user session (page navigation/refresh) what you collapse stays collapsed, default is expanded

Hide unregistered, unifies patch/subwatch title, persist card expanded 🤯

---

src/SmartComponents/SubscriptionsUtilized/Constants.js

Updating links in Subscriptions Watch widget. Old links are no longer working anywhere except prod-stable.

swatch: Update links

---

src/SmartComponents/PatchManager/PatchManagerCard.js

Before: On beta, Patch links were pointing to stable
After: On beta, Patch links are linking to /beta

Respect beta path on Patch card

---

src/AppConstants.js
src/SmartComponents/SubscriptionsUtilized/Constants.js

- Adds an `openshift` base constant
- Updates the Subscription card with relative path references for both `insights` plus `openshift` so they work with both `stable` and `beta` paths.
On beta, Subscription links were pointing to `stable`
On beta, Subscription links are linking to `beta`
Per discussion @rblackbu @bclarhk since Subscriptions doesn't have a landing page the default "app" link aims at RHEL

Respect beta path on Subscriptions card

---

src/SmartComponents/Vulnerability/VulnerabilityCard.js

Follow-up to #256. Update `affecting` URL parameter on vulnerability card. Vulnerability backend has been updated (all envs including prod) and there no need for this backwards compatibility. Fixes this weirdness:

Update URL parameters on vulnerability card

---

src/SmartComponents/PatchManager/PatchManagerCard.js

We have a bug related to the API column name change in production. The URL from dashboard to Patch should respect this change. This PR should fix the issue. It would be great if this can be reviewed ASAP.

fix url to Patch UI

---

config/dev.webpack.config.js
package-lock.json
package.json

There are ongoing issues caused by either `webpack-dev-server` itself or one of its dependencies with mutating the ESI tags inside the HTML templates with the actual content.
We do not know the cause of the issue nor how to fix it. This PR uses a chrome HTML template directly in local env. As this is approach will be used on products in the future, we can fast track it in this repository to unblock the development.

Use chrome HTML to fix failing ESI tag mutations.

---

src/App.js

Fixes a bug where:
1. Opening dashboard
2. Removing RBAC permissions
3. Opening dashboard again without refreshing
4. App would try to display cards based on outdated permissions cached in step 1
`getUserPermissions` has two arguments, first is `app` name (we pass empty string meaning all apps), and second is `bypassCache`, where true means do not cache, always get up-to-date permissions.

Do not cache RBAC permissions

---

src/AppConstants.js
src/Messages.js
src/SmartComponents/Drift/DriftCard.js
src/SmartComponents/Drift/utils.js

Previously we were adding only the baseline to the compare table, this PR will add associated system ids to the compare table as well.
We are limiting up to 1 baseline and 4 systems to be added to the drift table.
Added a tooltip to the button as well
Thanks

[DRFT-1006] Add systems to compare button

---

src/App.js

Almost a year ago, "Subscriptions user" role was introduced. It included finer-grained permission, `subscriptions:reports:read`. See https://github.com/RedHatInsights/rbac-config/commit/2d8d59e6ed358fda66beb7113c3833e60b53c8a9 . Subscriptions API was modified to recognize this permission in https://github.com/RedHatInsights/rhsm-subscriptions/commit/0426c894f9425dc0e11976b54790f03775ffe6ef . But it looks like we forgot about dashboard card which, so far, recognizes only `subscriptions:*:*`.
`subscriptions:reports:read` is offered through "Subscriptions user" role to all new users since... I don't know, probably sometime around Summit 2021.

Allow Subscriptions reader to see Subscriptions dashboard widget

---

src/SmartComponents/SystemInventory/SystemInventoryHeader.js

Resolves: [ESSNTL-3956](https://issues.redhat.com/browse/ESSNTL-3956);
Description:
The number of systems is different in the Inventory applcation when navigated from Dashboard 'Systems registered with Insights' link.
To test:
1. Visit dashboard
2. Observe the number of systems that has insights.
3. Click on the link 'Systems registered with Insights' that will bring you to inventory app.
4. Observe the number of systems on the table is the same.

fix(ESSNTL-3956): remove stale and fresh params from inventory url

---

src/SmartComponents/Vulnerability/VulnerabilityCard.js

Resolves [VULN-2489](https://issues.redhat.com/browse/VULN-2489).
Previously if AAP or MSSQL workload was selected the Vulnerability card would not work and would show error message:
` Vulnerability has experienced an error. Contact Red Hat support if the problem persists. `
Fixes API params to be boolean in accordance with [API docs](https://stage.foo.redhat.com:1337/beta/docs/api/vulnerability/v1#operations-default-manager\.dashboard_handler\.GetDashboard\.get).

Vulnerability card: Fix AAP and MSSQL workload filtering

---

build/messages/src/Messages.json
locales/translations.json
src/Messages.js
src/SmartComponents/SystemInventory/SystemInventoryHeader.js

In accordance to https://issues.redhat.com/browse/ESSNTL-3964 
This PR adds a Configure Integrations button next to the Register Systems button on the dashboard.
To test simply go to the dashboard, verify the button is there, and verify it sends you to` settings/integrations `

feat(ESSNTL-3964): Adds settings integration button

---

src/PresentationalComponents/ZeroState/ZeroState.js

Fixes https://issues.redhat.com/browse/ESSNTL-3647.
This disables the global filter on the static /insights/start page.
Navigate to /insights/start, and check that the global filter is disabled.

fix(/start page): Disable global filter

---

src/AppActions.js
src/AppConstants.js
src/AppReducer.js
src/SmartComponents/PatchManager/PatchManagerCard.js

The subtotals for the three advisory types - bugs, security and enhancements - are available in the `meta` structure of the request. This means that we do not have to make three requests to the Patch API in order to get the data necessary to build the Advisory Types pie chart.
This work basically generates a single request and stores the subtotals data.  The subtotal for each advisory type are then pulled out in the PatchManagerCard component.
Signed-off-by: Paul Wayper <paulway@redhat.com>

Reduce calls to Patch advisories to a single request

---

package-lock.json
package.json
src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedHelpers.js
src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedHelpers.test.js

The moment.js library is rather large and some network bandwidth can be saved by removing it from the project.  Its use is only minimal and its use replaced by functions from the built in Date library.

Remove moment.js library

---

src/SmartComponents/Drift/DriftEmptyState.js

Before, the button didn't behave as a link and didn't do anything after click.

fix: Fix the non-working Drift link button

---

config/prod.webpack.config.js

We are having a problem at build time where the webpack config is using beta paths even though our env var is set to BETA. I've audited the logs in the build and as far as I can tell everything was correct up to the point where we build dashboard's code, and then it just incorrectly chose beta. I don't *know* if this will fix our issues, but it follows what chrome uses:
https://github.com/RedHatInsights/insights-chrome/blob/e96d6e1801dc11755aabbdf1071fe7969c52de0e/config/webpack.config.js#L26
This is known to work there.

I do not trust javascript + env truthiness

---

src/Messages.js
src/SmartComponents/NewRules/NewRules.js

Ticket: https://issues.redhat.com/browse/VULN-2576
Mockup: https://www.sketch.com/s/4d721f7e-f57e-46e6-ba1c-739c0cad040e/a/09e9lyb?annotation=8acba49e-e913-4872-8fa5-f9b9287bc420#Comment
- removed the "View more" button because it navigated user to the detail of first listed CVE which was confusing for the users when there were multiple CVEs listed
- replaced pie chart with just a number of systems exposed
- added a text explaining how the number of systems exposed is calculated

Remove pie chart from latest critical notifications

---

src/PresentationalComponents/ZeroState/zeroStateConstants.js

In accordance with https://issues.redhat.com/browse/RHINENG-1465

fix(RHINENG-1465): Update Malware documentation link

---

src/PresentationalComponents/ZeroState/AppZeroState.js

This refactor allows us to move the logic from zero state federated module, into the module itself so that apps are cleaner and there is one source of truth.
This also allows for custom fetch conditionals. The app can do its own logic and pass the result of that into customFetchResults and it will set the zero state to true or false depending on the value passed in.
This also allows the clean up up code in the router section of apps so that in that section, isntead of the conditional currently it apps it would look something like this `<AppZeroState app={'advisor'} customFetchResults={true}>
<Suspense fallback={<Loading />}>
<Routes>
<Route path='/start' element={<ZeroState />} />
<Route path='/*' element={<Dashboard />} />
</Routes>
</Suspense>
</AppZeroState>`
Lastly this refactor …

refactor(ZeroState): Refactor zero state fed mod

---

config/overrideChrome.js
src/App.js
src/PresentationalComponents/Dashboard/Dashboard.js
src/PresentationalComponents/ZeroState/ZeroState.js
src/SmartComponents/SystemInventory/SystemInventoryHeader.js
src/Utilities/useBatchInventoryFetch.js

Navigate to the dashboards page, open up the network tab and filter got /host request.
In master, every other refresh will result in 22 calls when you clear or add a global filter. With this refactor is should be around 14.
Further work can be done for improvements. The currently global filters are 'updating' every time a file contains the connect function for the dashboard store. (5 files). Investigation into that would be the next step

refactor(RHINENG-8815): Refactor to reduce api calls

---

.eslintrc.yml
config/setupTests.js
package.json
src/AppConstants.js
src/PresentationalComponents/Dashboard/Dashboard.js
src/PresentationalComponents/DownloadReport/DownloadReport.js
src/PresentationalComponents/Template/ExpandableCardTemplate.js
src/SmartComponents/CentOs/CentOsCard.js
src/SmartComponents/CentOs/CentOsCard.test.js
src/SmartComponents/CentOs/EOLCountdownAlert.js
src/SmartComponents/CentOs/index.js

Implements https://issues.redhat.com/browse/RHINENG-8918.
Based on https://github.com/RedHatInsights/insights-dashboard/pull/480.
This adds a new widget to the main dashboard that alerts about CentOS upcoming EOL and also shows additional links, hosts count, etc.
1. Go to the dashboard
2. If your account has zero CentOS systems, the widget should show the alert, text with links and the button redirecting to the Tasks app
3. If you account has at least one CentOS systems, the widget should also show the CentOS hosts count
4. The widget should always be shown

feat(RHINENG-8918): Add CentOS card to the main dashboard

---

src/PresentationalComponents/Dashboard/Dashboard.js

Resolves: https://issues.redhat.com/browse/RHINENG-9387
This updates the page title to: 'Dashboard | RHEL'

chore(RHINENG-9387): update document title to Dashboard | RHEL

---

config/setupTests.js
src/App.js
src/App.test.js
src/PresentationalComponents/Dashboard/Dashboard.js
src/PresentationalComponents/PageLoading/PageLoading.js
src/PresentationalComponents/PermissionsProvider/PermissionsProvider.js
src/PresentationalComponents/ZeroState/AppSection.js
src/PresentationalComponents/ZeroState/AppSectionItems.js
src/PresentationalComponents/ZeroState/AppZeroState.js
src/PresentationalComponents/ZeroState/ZeroState.js
src/PresentationalComponents/ZeroState/ZeroStateBanner.js
src/PresentationalComponents/ZeroState/ZeroStateFooter.js
src/SmartComponents/Footer/Footer.js

This makes sure the Zero state banner is not shown during API requests. It also removes redux deprecated function `batch` as now React 18 defaults to batch state updates.
To test:
1. run the application
2. navigate to Dashboard page, observe that no zero state is shown even for milli-seconds if you have systems registered
3. navigate to some other app, and come back no zero state should be displayed
4. open some account without systems registered, observe that now zero state is shown

fix(RHINENG-9846): do not show zero-state while loading data

---

src/PresentationalComponents/DownloadReport/DownloadReport.scss
src/PresentationalComponents/IconInline/IconInline.scss
src/SmartComponents/CentOs/CentOsCard.js

Fixes https://issues.redhat.com/browse/RHINENG-10693.
This changes the link and text of the button for the state when account doesn't have any CentOS systems registered.

fix(CentOS card): Change the link for the CentOS card

---

src/SmartComponents/SystemInventory/SystemInventoryHeader.js

https://issues.redhat.com/browse/RHINENG-10939
The loading state now resembles the loaded version of the top bar and allows buttons to be clicked even before the Dashboard is loaded.

fix: Do not hide top buttons behind loading state

---

src/SmartComponents/Drift/DriftDropDown.js

The dropdown is inside the header component thus it inherited the increased font weight, but it should not have.

Fix Drift card dropdown being bold

---

src/DashboardRoutes.js
src/SmartComponents/Compliance/ComplianceCard.js
src/SmartComponents/PatchManager/PatchManagerCard.js
src/SmartComponents/Remediations/RemediationsCard.js
src/SmartComponents/ResourceOptimization/ResourceOptimizationCard.js

Some cards use spinners, some skeletons, some nothing
All cards use spinners

Add loading spinners

---

src/SmartComponents/ResourceOptimization/ResourceOptimizationCard.js

Previously, you could only click the text label under numbers in Resource optimization card to navigate to the ROS app. Now you can also click the numbers which is consistent with Advisor card. 
The change is just moving `InsightsLink` outside of the `Flex`.

Fix ROS cards number links being inconsistent

---

src/PresentationalComponents/ZeroState/AppZeroState.js
src/PresentationalComponents/ZeroState/AppZeroState.test.js

Theres is currently a small bug in production where 'total' is undefined in the base request from the api. This removes the brackets so that it simply grabs the object from the api and grabs the total. 
This is the slack thread: 
https://redhat-internal.slack.com/archives/C02T90PLJ5V/p1725048369737919

fix(sentryError): Fix network fetch error reported in sentry

---

src/PresentationalComponents/PermissionsProvider/PermissionsProvider.js

The new `advisor:*:read` permission needs to be accounted for in the permissions provider.

fix(RHINENG-8056): Advisor read permissions

---

src/PresentationalComponents/Dashboard/Dashboard.js
src/PresentationalComponents/ZeroState/zeroStateConstants.js

Hides the drift card with a feature flag due to its sunset as of October 1st. Removes zero-states related to Drift completely, as the probability of a user bumping them is very low.

chore: hide drift card and zero-state

---

src/PresentationalComponents/ZeroState/_zero-state.scss

Rather than grouping them in center, distribute them evenly. Parent object has max-height set up so it will never get too wild.
Before:
After:
_(Note: Repositories are already doing this, this is where the inspiration comes from)_

fix(ZeroState): Space items evenly
