RedHatInsights/insights-dashboard

- .travis.yml
- .travis/after_success.sh
Restructuring Travis to not use the encrypted variables on PRs. This should allow forks to contribute.
> Restructuring travis for PRs

- .travis/release.sh
- .travis/release_stable.sh
- src/App.js
- src/PresentationalComponents/Rules/Rules.js
- src/Routes.js
Also adds the missing '.git' when checking out repos in the travis build process
> fixes routes. Gets rid of extra dashboard in url

- package-lock.json
- package.json
- src/SmartComponents/Dashboard/Dashboard.js
- src/SmartComponents/Dashboard/_dashboard.scss
On hold until [The Dark component is added](https://github.com/RedHatInsights/insights-frontend-components/pull/102) and should be consumed to allow [abstraction of dashboard styles from Chrome.](https://github.com/RedHatInsights/insights-chrome/pull/34)
> updating components to use Dark

- src/PresentationalComponents/GaugeWidget/GaugeWidget.js
- src/PresentationalComponents/GaugeWidget/_ins-c-gauge-widget.scss
- src/SmartComponents/Dashboard/Dashboard.js
First example is not entitled and the second is not set up
> Adding app card variants: notEntitled & notSetUp

- package-lock.json
- package.json
- src/PresentationalComponents/GaugeWidget/GaugeWidget.js
> updating packages

- package-lock.json
- package.json
Page Header needs to have the `pf-c-foo` class on it instead of `pf-l-foo`, this updates the packages to be up to date for that.
> updating packages to pull in new classes from pageHeader

- src/PresentationalComponents/Dashboard/Dashboard.js
- src/PresentationalComponents/Dashboard/_dashboard.scss
- src/SmartComponents/Cards/_cards.scss
#26 
cc: @ncameronbritt @jeperry
> updating dashboard to use gallery instead of grid

- src/AppConstants.js
- src/SmartComponents/Cards/CostManagementCard.js
Cost Management API changed. Need to update code use latest format/urls.
Used `jalberts@redhat.com` against *ci* environment.
> Cost Management API changed. Need to update code use latest format/urls.

- src/entry-dev.js
- src/entry.js
* No UI changes
* Fixes wrong navigation on beta releases
> Fixes beta navigation

- src/PresentationalComponents/Dashboard/Dashboard.js
- src/SmartComponents/Cards/ComplianceCard.js
- src/SmartComponents/Cards/VulnerabilityCard.js
- src/Utilities/asyncComponent.js
This does not add Drift or Remediations cards
> Fixing bugs on dashboard

- .travis/custom_release.sh
- config/base.webpack.plugins.js
- config/webpack.common.js
* All changes to master automatically pushed to qa and ci beta
* Added travis branch to beta branches as well so we have correct build for beta releases
> Add QA release to auto travis

- src/index.html
Really simple commit. Just changing the title of the app to Dashboard
> Update tab title to Dashboard

- src/SmartComponents/Cards/ComplianceCard.js
- src/SmartComponents/Cards/VulnerabilityCard.js
- src/entry-dev.js
- src/entry.js
Once all data has been loaded calling `document.querySelectorAll('[data-ouia-safe=true]')` will query these elements:
> Add data-ouia-safe true to elements that are async loaded and to root element

- README.md
> Correct readme build url

- src/SmartComponents/Advisor/Advisor.js
- src/SmartComponents/Advisor/StackChart.js
related to https://projects.engineering.redhat.com/browse/RHCLOUD-5113
> Simplifies chart a lil bit, fixes urls 

- src/SmartComponents/Advisor/Advisor.js
- src/SmartComponents/Advisor/StackChart.js
- src/SmartComponents/Advisor/_Advisor.scss
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-5113
cc @kybaker
> Updates advisor card as per mocks

- profiles/local-frontend.js
local-frontend needs updating since the bundle has moved 😄
> Update section from "rhel" to "insights"

- build/messages/src/Messages.json
- locales/data.json
- locales/translations.json
- src/Messages.js
- src/PresentationalComponents/Dashboard/_dashboard.scss
- src/SmartComponents/Compliance/ComplianceCard.js
> fix(compliance): update text and add links

- src/App.js
Moves all of the chrome stuff into an async function and does an await on the getUser() so RBAC doesn't throw 401.
> make init async and check user

- src/AppConstants.js
travis is being silly, ignore him ❌
> Update ui-base because it changed

- .travis.yml
- package-lock.json
Updated travis to use stages and removes the after_success flag
> update travis yml to remove after_success

- src/PresentationalComponents/Dashboard/Dashboard.js
> Remediation card isn't ready, lets hide it, auto arrange imports

- src/SmartComponents/Vulnerability/Constants.js
- src/SmartComponents/Vulnerability/VulnerabilityCard.js
1. removed the links at the right top, since they did nothing
2. added CVSS link for the chart
@kybaker
> fix(vulnerability card): Add cvss score links

- src/SmartComponents/Compliance/ComplianceCard.js
Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-553
Old behavior:
@christiemolloy @ryelo @AllenBW @dLobatog @bastilian 
@kybaker
> Compliance score is out of 100, not 1

- src/App.js
- src/PresentationalComponents/Dashboard/Dashboard.js
Adds a check for subscription watch -- this is gated by org admin status
[dashboard blows up or loads forever]
[if needed]
@kybaker
> add check for org admin

- src/SmartComponents/Compliance/ComplianceCard.js
Fixes label on compliance card
I think https://github.com/RedHatInsights/insights-dashboard/pull/103 just fixed the actual pie chart percentage, this updates the actual score displayed outside the chart
@kybaker
> fix compliance card

- src/AppConstants.js
param cleanup for the sake of clarity
> Culls advisor incident call params

- .gitignore
remove the non ignore for build/../messages
> ignore messages

- src/Store/index.js
SO we have a bunch of apis, sometimes their 403 responses look different, so instead of breaking when we see an unexpected 403 response, lets just display that it was 403, rely on the dashboard card to say whats broken
none CUZ IT WAS BROKEN
[if needed]
@kybaker
> All these different apis have different error response formats

- src/PresentationalComponents/FailState/FailState.js
- src/PresentationalComponents/FailState/FailState.scss
- src/SmartComponents/PatchManager/PatchManagerCard.js
- src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
- src/SmartComponents/SystemInventory/SystemInventoryCard.js
Changes the text in the top cards for the fail state
@kybaker
> update empty state on top to use small text

- src/PresentationalComponents/DeniedState/DeniedState.js
Removes lock icon from no permission state #134 
@kybaker
fixes #134
> remove lock icon from permission state

- package-lock.json
- package.json
- src/Store/index.js
- src/entry-dev.js
- src/entry.js
PMs and TMMs requested that we don't show toast alerts since we already display these messages in the respective card. This should make it seem less "scary" to the users when an error happens because we have graceful handling! 
> remove notifications portal

- src/ChartTemplates/StackChart/StackChartTemplate.js
fixes https://projects.engineering.redhat.com/browse/RHCLOUD-6406
> Fixes stack chart tooltip size, font, and position 👷‍♀️🥳🥺

- src/ChartTemplates/StackChart/StackChartTemplate.js
> Refactors stack chart label to now have link underline 

- src/ChartTemplates/StackChart/StackChartTemplate.js
> Fixes stackchart redirect 🤗💯👍🏽

- src/ChartTemplates/StackChart/StackChartTemplate.js
- src/SmartComponents/Remediations/RemediationsCard.js
- src/SmartComponents/Remediations/RunStatus.js
nothing changes, cept more ids in mo places (and a lil bitta auto formatting)
####
> Adds ids to stack chart and remediations run card in support of pendo

- src/App.js
Activate RBAC permissions for Subscription Watch.
> Activate RBAC permissions for Subscription Watch

- src/entry-dev.js
- src/entry.js
dupe https://github.com/RedHatInsights/insights-advisor-frontend/pull/737/
> Reduce intl logging by trimming locals

- src/App.js
dupe of https://github.com/RedHatInsights/insights-advisor-frontend/pull/751/
for @dkuc
> For Dan, unencode tags

- src/App.js
- src/AppActions.js
- src/AppConstants.js
- src/AppReducer.js
- src/SmartComponents/Advisor/Advisor.js
fixes https://issues.redhat.com/browse/ADVISOR-1364
> Adds workload to app state, advisor card to consume/use

- package-lock.json
- package.json
- src/App.js
- src/ChartTemplates/PieChart/PieChartTemplate.js
- src/PresentationalComponents/PageLoading/PageLoading.js
- src/SmartComponents/Advisor/Advisor.js
fixes https://issues.redhat.com/browse/ADVISOR-668
> Center app loading screen 

- src/SmartComponents/Advisor/Advisor.js
> Reconfigures advisor card workload filter to now function correctly ✅🥰

- src/Messages.js
- src/SmartComponents/SystemInventory/SystemInventoryCard.js
- src/SmartComponents/SystemInventory/SystemInventoryCard.scss
If user doesn't have access to inventory error is thrown and error card is shown. We want to tell user more information, why that happend so let's show them that they have no access to inventory.
**Wide screen**
**Mobile screen**
@kybaker @mmenestr
> Show empty state for inventory card if user has no access to inv

- build/messages/src/Messages.json
- locales/translations.json
- src/Messages.js
- src/SmartComponents/Advisor/Advisor.js
- src/SmartComponents/Compliance/ComplianceCard.js
- src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
fixes https://issues.redhat.com/browse/ADVISOR-1395
also updates advisor card pie to have a nicer zero state
> Cards that do not support workloads now indicate when they're selected 🤗

- src/App.js
- src/AppActions.js
- src/AppConstants.js
- src/AppReducer.js
- src/SmartComponents/SystemInventory/SystemInventoryCard.js
This PR adds support for SID part of global filter and applies it for inventory card.
@ryelo @AllenBW
> Use new global filter mapper format and pass SID filter to inv

- src/App.js
- src/SmartComponents/Advisor/Advisor.js
- src/SmartComponents/PatchManager/PatchManagerCard.js
- src/SmartComponents/SystemInventory/SystemInventoryCard.js
- src/Utilities/Common.js
fixes https://issues.redhat.com/browse/ADVISOR-1405
reverted app.js global filter handling to suite apps in place
> Patch card to support workloads/tagging/sids 🚤✅🥰

- src/index.html
https://issues.redhat.com/browse/RHCLOUD-10547
> Update tab title

- package-lock.json
- package.json
- src/App.scss
- src/AppEntry.js
- src/PresentationalComponents/Dashboard/Dashboard.js
- src/PresentationalComponents/Dashboard/_dashboard.scss
- src/PresentationalComponents/NumberData/NumberData.scss
- src/PresentationalComponents/Template/DataListItemTemplate.js
- src/PresentationalComponents/Template/DataListItemTemplate.scss
- src/PresentationalComponents/Template/ExpandableCardTemplate.js
- src/PresentationalComponents/Template/TemplateCard.js
- src/PresentationalComponents/Template/TemplateCard.scss
- src/SmartComponents/Advisor/Advisor.js
- src/SmartComponents/Advisor/Constants.js
- src/SmartComponents/Footer/Footer.js
- src/SmartComponents/NewRules/NewRules.js
- src/SmartComponents/NewRules/NewRules.scss
- src/SmartComponents/SystemInventory/SystemInventoryHeader.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.scss
- src/SmartComponents/Vulnerability/VulnerabilityCard.js
- src/Utilities/Common.js
Refines CSS per @kybaker request
@AllenBW here's where I need support
@ryelo @AllenBW
@kybaker
> added masonry layout

- src/SmartComponents/Vulnerability/VulnerabilityCard.js
This link should take user to the vulnerability landing page with some filters applied
> use correct link to vulnerability application

- README.md
- config/dev.webpack.config.js
- package.json
fixes https://issues.redhat.com/browse/ADVISOR-1624
its all @rvsia 's fault, he's the brilliant fella making this possible
> Adds start:proxy, running the frontend without proxy terminal 🤯🥑💌

- src/SmartComponents/Vulnerability/VulnerabilityCard.js
fixes https://issues.redhat.com/browse/VULN-1580?focusedCommentId=16014378&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16014378
> Vuln card url switcheroo 👘💍

- src/SmartComponents/Vulnerability/VulnerabilityCard.js
Adding breakdown of exploits by CVSS:
> provide breakdown of known exploits by CVSS on vuln card

- src/SmartComponents/Vulnerability/VulnerabilityCard.js
> Simplify vuln chart legend

- src/PresentationalComponents/ZeroState/ZeroState.js
fixes https://issues.redhat.com/browse/ADVISOR-1724
> Fix security url, removes insights base

- src/PresentationalComponents/Dashboard/dashboard.scss
fixes https://issues.redhat.com/browse/ADVISOR-1743
> Increases dashboard max-width as per ux rec 🍷㉿

- src/SmartComponents/Vulnerability/VulnerabilityCard.js
there was a filtering in update on Vulnerability side - Dashboard needs
to be switched as well. This is 1st commit which is backwards compatible
and also ensures nothing will break once Vulnerability updates
production.
This commit will be followed by another one once Vulnerability
production is updated which will remove the part used for compatibility.
> vulnerability: update URL param

- src/PresentationalComponents/Dashboard/Dashboard.js
jira: https://issues.redhat.com/browse/RHCLOUD-16048
This is part of a FedRamp effort. More details can be found here: https://issues.redhat.com/browse/RHCLOUD-14323
> Hide subscriptions card in fedramp env.

- src/SmartComponents/Compliance/ComplianceCard.js
* Adds OS version
* Removes "description"
* Updates "view more" link
> fix(ComplianceCard): RHICOMPL-1026 - Minor 💅

- src/SmartComponents/Compliance/ComplianceCard.js
Fixes the link to properly link to the create policy wizard.
> fix(ComplianceCard): RHICOMPL-1733 - Correct link to create policy

- src/PresentationalComponents/NumberDescription/NumberDescription.js
- src/SmartComponents/Advisor/Advisor.js
- src/SmartComponents/Compliance/ComplianceCard.js
- src/SmartComponents/PatchManager/PatchManagerCard.js
- src/SmartComponents/Remediations/RemediationsCard.js
- src/SmartComponents/Remediations/RunStatus.js
- src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.js
- src/SmartComponents/Vulnerability/VulnerabilityCard.js
- src/Utilities/hooks/useChromePush.js
https://issues.redhat.com/browse/RHCLOUD-16624
> Insights dashboard page reload fix

- locales/data.json
- locales/translations.json
- src/App.js
- src/AppActions.js
- src/AppConstants.js
- src/AppReducer.js
- src/Messages.js
- src/PresentationalComponents/Dashboard/Dashboard.js
- src/SmartComponents/ResourceOptimization/ResourceOptimizationCard.js
Added card in the Insights Dashboard to show details related to Resource Optimization service.
Jira Card: https://issues.redhat.com/browse/RHIROS-36
**Use Case: Nothing is setup** 
**Use Case: Systems with suggestions + waiting for data**
Sample JSON output of `/api/ros/v1/is_configured` API
```
{
"success": true,  
"code": "SYSTEMSEXIST", 
"count": 2, 
"systems_stats": {
"waiting_for_data": 0, 
"with_suggestions": 2
}
}
```
**Note:** 
1) ~~Since we need to update the back-end API is_configured to send few more details related to ROS, the changes will be soon available and hence I have added `fixme` for same. Please feel free to review the rest of the code and let me know any comments/suggestions~~ **The /ros/v1/is_configured API is available in CI/QA environments as of today.**
2) …
> RHIROS-36: add Resource Optimization card on dashboard

- config/dev.webpack.config.js
- config/setupTests.js
- src/App.scss
- src/AppActions.js
- src/AppConstants.js
- src/AppReducer.js
- src/Messages.js
- src/PresentationalComponents/Dashboard/Dashboard.js
- src/SmartComponents/Drift/DriftCard.js
- src/SmartComponents/Drift/DriftCard.scss
- src/SmartComponents/Drift/DriftDropDown.js
- src/SmartComponents/Drift/DriftEmptyState.js
- src/SmartComponents/Drift/utils.js
Here is a updated video on how the dashboard is working!
https://user-images.githubusercontent.com/13910652/150391530-a830ccfa-91e8-4e2c-9a28-f72f41e381ad.mov
> Add Drift dashboard

- .travis.yml
- locales/data.json
- locales/translations.json
- package-lock.json
- package.json
- src/Messages.js
- src/SmartComponents/ResourceOptimization/ResourceOptimizationCard.js
Updated the Resource Optimization (ROS) card in the dashboard with numbered links. 
I have created the [ROS side PR](https://github.com/RedHatInsights/ros-frontend/pull/89) here. If everything looks good we can merge this as until [ROS PR](https://github.com/RedHatInsights/ros-frontend/pull/89) is not merged it wont work end to end but not processing query params won't break anything.
**jira link:** https://issues.redhat.com/browse/RHIROS-447
https://drive.google.com/file/d/1-OCczzQYK_lDo2sSyO7I3bbGfEf_UNZf/view?usp=sharing
> RHIROS-488 updated ROS card to add individual links

- src/Messages.js
- src/SmartComponents/Drift/DriftEmptyState.js
Add message to user enable baseline notifications in dashboard empty state
> [DRFT-1031] Add new message to Drift dashboard empty state

- src/SmartComponents/Drift/DriftCard.js
- src/SmartComponents/Drift/DriftCard.scss
Fixed spacing between the dropdown and expand button
Added bold font to "Top 5..." 
Before:
After:
> [DRFT-1039] Fix spacing, font weight

- src/SmartComponents/Drift/DriftCard.js
- src/SmartComponents/Drift/DriftCard.scss
Merge master into master-stable
> [DRFT-1039] Fix spacing, font weight (#301)

- src/PresentationalComponents/Dashboard/Dashboard.js
- src/SmartComponents/Advisor/Advisor.js
- src/SmartComponents/PatchManager/PatchManagerCard.js
- src/SmartComponents/SystemInventory/SystemInventoryCard.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.js
- src/SmartComponents/Vulnerability/VulnerabilityCard.js
- src/Utilities/Common.js
This PR adds support for the Ansible Automation Platform and Microsoft SQL global filters.
I have removed the empty state for the time being as we will be refactoring some of the code in Dashboard to improve global filters.
> Add AAP and MSSQL global filter support

- config/setupTests.js
- package-lock.json
- package.json
- src/PresentationalComponents/TimeStamp/TimeStamp.js
- src/SmartComponents/Drift/DriftCard.js
Had to update packages like in other apps. Also added packages which will be needed for testing.
> Update packages for working snapshot tests

- frontend.yml
`/insights/` is the wrong route root and causes a 500. `/apps/` is the correct base
> Update template to use apps route

- package-lock.json
- package.json
2 critical CVEs, 4 high CVEs -> 0 CVEs
> Resolve package CVEs

- src/AppConstants.js
- src/SmartComponents/Remediations/RemediationsCard.js
- src/SmartComponents/Remediations/RunStatus.js
Implements https://issues.redhat.com/browse/RHIF-142
Depends on the related PR going into the remediations backend: https://github.com/RedHatInsights/insights-remediations/pull/297
> Remediations card optimization related to RHIF-141 & RHIF-142

- src/App.js
- src/AppActions.js
- src/AppConstants.js
- src/SmartComponents/Drift/DriftCard.js
https://issues.redhat.com/browse/RHIF-124
> feat(dashboard): adopt usechrome hook

- config/prod.webpack.config.js
This mirrors https://github.com/RedHatInsights/insights-dashboard/pull/355/files - until this is merged prod-beta will be broken
> Fix beta in routes in beta builds

- src/AppConstants.js
- src/SmartComponents/Remediations/RemediationsCard.js
- src/SmartComponents/Remediations/RunStatus.js
Not to be merged until this remediations API PR https://github.com/RedHatInsights/insights-remediations/pull/297 has been merged first.
> Remediations card optimization related to RHIF-141 & RHIF-142, take 2

- config/prod.webpack.config.js
> Add missing root app expose config in prod.

- src/PresentationalComponents/ZeroState/ZeroStateBanner.js
- src/PresentationalComponents/ZeroState/zeroStateConstants.js
This PR simply adds the constants for the apps to implement Zero State.
> Add app constants for Zero State

- config/prod.webpack.config.js
- src/Messages.js
- src/PresentationalComponents/ZeroState/AppSection.js
- src/PresentationalComponents/ZeroState/AppSectionItems.js
- src/PresentationalComponents/ZeroState/ZeroStateBanner.js
- src/PresentationalComponents/ZeroState/zeroStateConstants.js
The text is a placeholder for the moment until we get final copy. To test, go here: https://github.com/RedHatInsights/insights-dashboard/blob/master/src/PresentationalComponents/Dashboard/Dashboard.js#L42 and add a ! in front of the check.
> feat(RHIF-240): Add Other Apps section card to zero state

- config/prod.webpack.config.js
- src/PresentationalComponents/RegisterSystemList.js
- src/PresentationalComponents/ZeroState/AppZeroState.js
- src/PresentationalComponents/ZeroState/ZeroStateBanner.js
- src/PresentationalComponents/ZeroState/ZeroStateFooter.js
- src/PresentationalComponents/ZeroState/_zero-state.scss
- src/PresentationalComponents/ZeroState/zeroStateConstants.js
This PR adds the remaining constants from the mocks, Allows you to import 1 file as opposed to 3 different ones when importing the federated modules, and makes the 2nd page of the 'Start using insights modal' more dynamic and allow for some of the mocks instructions.
https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/prototype/a/AEF47CA9-8F00-40FC-B39B-3B989D3F83FD
> feat(RHIN-830):Zero state constants + more dynamic

- src/PresentationalComponents/ZeroState/AppSection.js
- src/PresentationalComponents/ZeroState/AppSectionItems.js
- src/PresentationalComponents/ZeroState/ZeroStateBanner.js
- src/PresentationalComponents/ZeroState/ZeroStateFooter.js
- src/PresentationalComponents/ZeroState/_zero-state.scss
- src/PresentationalComponents/ZeroState/zeroStateConstants.js
Some minor layout enhancements
> Change title levels, fix fonts and other layout issues

- build/messages/src/Messages.json
- locales/translations.json
- src/Messages.js
- src/PresentationalComponents/RegisterSystemList.js
- src/PresentationalComponents/ZeroState/AppSectionItems.js
- src/PresentationalComponents/ZeroState/AppZeroState.js
- src/PresentationalComponents/ZeroState/ZeroStateBanner.js
- src/PresentationalComponents/ZeroState/ZeroStateFooter.js
- src/PresentationalComponents/ZeroState/zeroStateConstants.js
This updates the federated module to do a few things
1. It updates constants and apps to the new mocks.
2. It allows for links within text in the commands as some mocks call for this
3. renders padding conditionally on certain 'commands' in zero state when required, also called for in mocks
4. Updates All apps to corrects steps
5. Adds Remediations and Images ZeroState'
> fix(ZeroState): Update zero state according to new mocks

- src/PresentationalComponents/RegisterSystemList.js
- src/PresentationalComponents/ZeroState/zeroStateConstants.js
https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/nQQYmWp#Inspect
> Update commands via new mocks

- src/PresentationalComponents/RegisterSystemList.js
In an attempt to fix containerization issue with fed module
> test white space

- src/App.js
> chore: remove this commit after summit

- src/PresentationalComponents/ZeroState/zeroStateConstants.js
Fixing non-working link to point on Supported SSGs article on Zero state
> fix(ComplianceDoc): RHICOMPL-3781 - Fix unsupported doc link

- config/cypress.webpack.config.js
- cypress/support/commands.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.cy.js
I added a cypress command that allows to mount component easier and provide components with suspense
> feat(cypress): command to mount components easily

- config/prod.webpack.config.js
This updates the prod-webpack config to use the latest condition introduced in patchman to decide Beta build vs stable build. After this PR is merged, a new image will be created and we will use it for deployment on prod-stable.
> fix: update prod-webpack config with correct build condition

- src/PresentationalComponents/ZeroState/zeroStateConstants.js
Adds inventory zero state + updates images zero state
> chore(RHIN-830): Add inventory zero state

- src/PresentationalComponents/Dashboard/Dashboard.js
A partial cause of https://issues.redhat.com/browse/RHIF-207 is that the document title isnt updated properly. This PR introduces the chrome hook.
Associated Jira ticket: # (RHIF-269)
Navigate to the home page and verify that the document changes appropriately
> fix(RHIF-269): adopt chrome updateDocumentTitle hook

- build/messages/src/Messages.json
- locales/translations.json
- src/Messages.js
- src/PresentationalComponents/ZeroState/zeroStateConstants.js
Ticket: [RHIF-200](https://issues.redhat.com/browse/RHIF-200)
[Tasks PR](https://github.com/RedHatInsights/tasks-frontend/pull/87)
> feat(ZeroState): RHIF-200 - Add Tasks to ZeroState

- src/PresentationalComponents/ZeroState/zeroStateConstants.js
In accordance to the updated mocks found here: https://docs.google.com/document/d/1FGuzbL2jyRmn_coYD5Z_o3d0MhOf1vQDT46NQvsfPyA/edit 
this updates remediations zero state
> fix(RHIF-199): Update Remediations zero state copy

- src/PresentationalComponents/ZeroState/ZeroStateBanner.js
This will simplify testing with iqe plugins.
> Add OuiaId for ZeroState app custom title

- src/SmartComponents/Vulnerability/VulnerabilityCard.js
https://issues.redhat.com/browse/VULN-2831
The link has `vulnerability` twice in it
https://console.stage.redhat.com/preview/insights/vulnerability/vulnerability/cves?affecting=true&rule_presence=true
> Fix Vulnerability card link

- cypress/fixtures/edgeHosts.json
- cypress/fixtures/featureFlags.json
- cypress/support/interceptors.js
- src/AppActions.js
- src/AppConstants.js
- src/AppReducer.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.cy.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.js
Fixed totals to match sum of systems in inventory
> fix(InventoryHeader): RHINENG-2743 fix displayed totals

- src/Messages.js
- src/SmartComponents/SystemInventory/EdgeDevicesWarning.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.cy.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.js
Instead of inventory totals containing edge devices, display warning that the devices are not included
> fix(InventoryHeader): RHINENG-2743 replace edge totals with edge warning

- src/SmartComponents/SystemInventory/SystemInventoryHeader.js
https://issues.redhat.com/browse/RHINENG-9423
> Link "Configure integations" button to Communications tab

- src/SmartComponents/CentOs/CentOsCard.js
https://issues.redhat.com/browse/RHINENG-9607
> CentOS conversion card, move toggle to the right

- babel.config.js
- src/App.js
- src/AppEntry.js
- src/DashboardRoutes.js
- src/PresentationalComponents/Dashboard/Dashboard.js
- src/SmartComponents/SystemInventory/SystemInventoryHeader.cy.js
- src/SmartComponents/Vulnerability/VulnerabilityCard.cy.js
The store appears to change every time the App is rendered this will prevent the store from changing in these cases.
The store changing caused multiple unnecessary rerenders and duplicate requests to APIs, when changing the global filter. This will address the issue.
**How to test**:
1) Open the dashboard
2) Add and remove global filter(s)
3) Observe the number of requests and compare with the number of request on actual stage (or master)
> fix(App): Improve loading behaviour

- src/SmartComponents/Advisor/Advisor.js
> Improve Advisor card loading skeleton

- src/SmartComponents/Vulnerability/VulnerabilityCard.js
> Improve Vulnerability card loading skeleton

- src/SmartComponents/Vulnerability/VulnerabilityCard.js
https://issues.redhat.com/browse/RHINENG-12218
> fix(Vulnerability card): Fix race condition leading to invalid affecting filter

- src/AppConstants.js
- src/SmartComponents/Compliance/ComplianceCard.js
We will need to merge and release it only after we release v2 in prod
> feat(RHINENG-14391): Make Compliance use APIv2

- .github/workflows/sentry.yml
- .gitignore
- fec.config.js
- package-lock.json
- package.json
This onboards dashboard to sentry to recieve proper error reporting/routing, as well as the automation workflow that sends debugIDs up on a merge to master + sourceMap automation when a release is made too prod
> feat(RHINENG-15382): Onboard Dashboard to Sentry

- package.json
Add verify script back to resolve pipeline issues
> add verify script to package.json

- cypress/fixtures/advisorRuleDashboard.json
- cypress/fixtures/advisorRulesDashboard.json
- cypress/fixtures/advisorSystemsDashboard.json
- cypress/support/interceptors.js
- package.json
- src/SmartComponents/Advisor/Advisor.cy.js
Related to the card [RHINENG-16630](https://issues.redhat.com/browse/RHINENG-16630)
> Add Cypress coverage to Advisor card
